#static code analysis by sonarqube
- name: 'maven:3.6.1-jdk-8'
  entrypoint: 'bash'
  args:
    - -c
    - |
      unset MAVEN_CONFIG \
      && echo "104.199.71.165 sonarqube.ct.blue.cdtapps.com" > /etc/hosts \
      && mvn sonar:sonar -q -Dsonar.login=5531b1a2d571c0482a3d45f605830e08ccf5f245 \
      '-Dsonar.projectKey=${_SONAR_PROJECT_KEY}' \
      '-Dsonar.projectName=gcp-cloudbuild' \
      '-Dsonar.host.url=${_SONAR_HOST_URL}' \
      '-Dsonar.qualitygate.wait=true' \
      'allow_failure: true'
  dir: '/'
  id: 'sonarqube-analysis'