steps:
  - name: 'gcr.io/cloud-builders/maven'
    id: 'Build and SonarQube Analysis'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install SonarScanner
        curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
        unzip /tmp/sonar-scanner.zip -d /tmp/
        export PATH=$PATH:/tmp/sonar-scanner-4.7.0.2747-linux/bin
        
        # Run SonarQube analysis
        sonar-scanner \
          -Dsonar.projectKey=${_SONAR_PROJECT_KEY} \
          -Dsonar.sources=.
          -Dsonar.host.url=${_SONAR_HOST_URL} \
          -Dsonar.login=${_SONAR_TOKEN}
          
        # Optional: Additional actions, like publishing the results to Cloud Storage or Slack
        # gsutil cp sonar-report.json gs://your-bucket/sonar-reports/
        
timeout: '1200s'  # Set the timeout for your build process

# Substitutions to be used in Cloud Build

# Optionally, you can define the trigger based on your repository's needs
# You would need to create a trigger in Cloud Build that activates on code changes
