steps:
  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/mythic-delight-434312-r1/cloud-builf-img:v1.0.0', '.'
    ]

images:
  # Specify the Docker image to save
  - 'gcr.io/mythic-delight-434312-r1/cloud-builf-img:v1.0.0'

options:
  logging: CLOUD_LOGGING_ONLY

