#static code analysis by sonarqube
steps:
  - name: 'maven:3.6.1-jdk-8'
    entrypoint: 'bash'
    args:
      - -c
      - |
        unset MAVEN_CONFIG \
        && echo "104.199.71.165 sonarqube.ct.blue.cdtapps.com" > /etc/hosts \
        && mvn sonar:sonar -q -Dsonar.login=${_SONAR_HOST_URL} \
        '-Dsonar.projectKey=${_SONAR_PROJECT_KEY}' \
        '-Dsonar.projectName=gcp-cloudbuild' \
        '-Dsonar.host.url=${_SONAR_HOST_URL}' \
        '-Dsonar.qualitygate.wait=true' \
    dir: '/'
    id: 'sonarqube-analysis'
options:
  logging: CLOUD_LOGGING_ONLY