steps:
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=http://34.72.166.147:9000/'
    - '-Dsonar.login=${_SONAR_TOKEN}'
    - '-Dsonar.projectKey=${_SONAR_PROJECT_KEY}'
    - '-Dsonar.sources=.'
tags: ['cloud-builders-community']