steps:
  - name: 'sonarsource/sonar-scanner-cli'  # Using the SonarScanner Docker image
    id: 'SonarQube Analysis'
    env:
      - 'SONAR_HOST_URL=${_SONARQUBE_URL}'  # Substitution for the SonarQube URL
      - 'SONAR_LOGIN=${_SONAR_TOKEN}'  # Substitution for the SonarQube authentication token
    args:
      - '-Dsonar.sources=.'  # Define the sources directory, you can modify this if needed
# Path to the repository in your build environment

timeout: '1200s'  # Set the timeout for your build process

options:
  logging: CLOUD_LOGGING_ONLY

